version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tire-optimizer-initial-setup"
s3_bucket = "tiresopt-deploy-anglo"
s3_prefix = "bucket"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
# aws cloudformation delete-stack --stack-name tire-optimizer-initial-setup