version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tire-optimizer-anglobronces-buckets"
s3_bucket = "sam-deploy-bucket-tire-optimizer"
s3_prefix = "bucket"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"